# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

---
gcp:
  project: clu-self-hosted-playground
  cred_content: "{{ lookup('file', '/service-account.json') }}"
  bucket_name: clu-gcp-k3s
  region: europe-west3
  zone: europe-west3-a
  machine_type: c2-standard-4
